# application
server:
  port: 10469
spring:
  application:
    name: aa1
  # 配置数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test01?characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis-plus:
  # 扫描 Mapper.xml 文件
  mapper-locations: classpath*:mapper/*.xml
  # 配置文件位置
  config-location: classpath:mybatis-config.xml
  # 设置别名的路径,可避免写全限定类名
#  type-aliases-package:


#debug: true
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848

## 文档
#knife4j:
#  enable: true
#  openapi:
#    title: Knife4j 文档
#    description: 文档测试
#    email: xiaoymin@foxmail.com
#    concat: test
#    url: https://docs.xiaominfo.com
#    version: v4.0
#    license: Apache 2.0
#    license-url: https://stackoverflow.com/
#    terms-of-service-url: https://stackoverflow.com/
#    group:
#      test1:
#        group-name: 分组名称
#        api-rule: package
#        api-rule-resources:
#          - com.knife4j.demo.new3
